### ISSUE TITLE
losing precision on  lower numbers

### ISSUE THREAD

**Issue by xfoxawy** [nikolaydubina/fpdecimal#22]
is there a way to fix losing precision on lower floats
for example
```
fpdecimal.FromFloat(0.0705)
```
results to `0.0704` output

my fraction digits is set to 4
```
func init() {
	fpdecimal.FractionDigits = 4
}

```

**Comment by nikolaydubina** [comment]
If you have float already, not much you can do.

Try to avoid float in first place. Read directly from string.

**Comment by nikolaydubina** [comment]
@xfoxawy this is supported now
