### ISSUE TITLE
Equal()

### ISSUE THREAD

**Issue by vanodevium** [nikolaydubina/fpdecimal#6]
It would be good to have such a method as well

**Comment by nikolaydubina** [comment]
Equality is tested by Go equality operator.

Could you provide why / when you would need Equal()?

**Comment by vanodevium** [comment]
In my case, this is needed for maximum ease when switching from shopspring/decimal to your library.

Also it is logic part of comparison methods:

- Equal
- LessThanOrEqual
- LessThan
- GreaterThanOrEqual
- GreaterThan

It will also be a bit strange if I use comparison methods everywhere, but for equality I will write **==** :) Imho

**Comment by vanodevium** [comment]
@nikolaydubina Can I make PR?

**Comment by nikolaydubina** [comment]
sure. lets add it !
