### ISSUE TITLE
Pointer receivers

### ISSUE THREAD

**Issue by vanodevium** [nikolaydubina/fpdecimal#8]
```
func (a Decimal) Float64() float64 { return float64(a.v) / 1000 }
```
What is the reason that you declared methods on values and not on references?
```
func (a *Decimal) Float64() float64 { return float64(a.v) / 1000 }
```
> asterisk before Decimal

Also, my IDE shows me a warning on each method:
**Struct Decimal has methods on both value and pointer receivers. Such usage is not recommended by the Go Documentation.**

**Comment by nikolaydubina** [comment]
Only `UnmarshalJSON` is using pointer receiver. So it is ok !

**Comment by nikolaydubina** [comment]
Will keep this issue open, to collect if more people want this and documentation on motivation.

**Comment by nikolaydubina** [comment]
no. performance is same: https://github.com/nikolaydubina/go-bench-receiver


this is to avoid handling nil pointer receiver scenario
